### ISSUE TITLE
Follows Redirects Outside shouldCrawl Function

### ISSUE THREAD

**Issue by marshmellow1328** [antivanov/js-crawler#8] opened 2015-09-03 14:11 UTC
If a page returns a redirect, the crawler automatically follows the redirect url without validating it against the shouldCrawl function.

This may be a separate concern, but it also seems to get confused by relative urls on the resulting page if the redirect went to a different domain. So if www.example.com returns a 301 to www.different.com and www.different.com has "/about" as a relative link, js-crawler thinks it needs to crawl www.example.com/about instead of www.different.com/about.

**Comment by antivanov** [comment] 2015-09-06 17:15
Good points, looks like redirects are not handled quite the way they should be. We use the 'request' https://github.com/request/request library that does redirects, I will investigate whether it provides some APIs to make the desired changes to the redirect behavior. Or maybe we even need some other library if 'request' is not flexible enough.

**Comment by antivanov** [comment] 2015-09-08 20:35
Fixed the second issue 

>it also seems to get confused by relative urls on the resulting page if the redirect went to a different >domain. So if www.example.com returns a 301 to www.different.com and www.different.com has >"/about" as a relative link, js-crawler thinks it needs to crawl www.example.com/about instead of >www.different.com/about.

in the commit https://github.com/antivanov/js-crawler/commit/877cf7a73aa8a282c65d9fd9f984c5d523ea6660, now redirects to a different domain are properly handled

The `shouldCrawl` redirect issue will be fixed in a separate commit

**Comment by marshmellow1328** [comment] 2015-09-10 15:16
I'm getting a "Cannot read property 'request' of undefined" error on line 129 of crawler. A generic scenario that hits this error is crawling https://www.yahoo.com.

**Comment by antivanov** [comment] 2015-09-11 19:08
"Cannot read property 'request' of undefined" seems like a regression after the latest changes, the errors are not handled properly. I will commit and publish a fix for the regression shortly.

However, in the case of Yahoo I get 'ERROR http://www.yahoo.com [Error: CERT_UNTRUSTED]'
Need to investigate this issue a bit more.

```javascript
var Crawler = require("js-crawler");

new Crawler().configure({depth: 2}).crawl("http://www.yahoo.com",
  function onSuccess(page) {
    console.log('SUCCESS', page.url);
  },
  function onFailure(status) {
    console.log('ERROR', status.url, status.error);
  }
);
```

**Comment by antivanov** [comment] 2015-09-11 20:24
Fixed the "Cannot read property 'request' of undefined" and [Error: CERT_UNTRUSTED] issues.

**Comment by antivanov** [comment] 2015-09-14 21:20
Closing the issue, please, reopen it if some other concerns were not addressed or the solution does not work for you.

**Closed by antivanov** 2015-09-14 21:20 UTC
Labels: enhancement, question
