### ISSUE TITLE
Network Challenges with Depth > 2

### ISSUE THREAD

**Issue by marshmellow1328** [antivanov/js-crawler#9] opened 2015-09-03 16:57 UTC
I'm starting here because I can't figure this out to even know where to start looking. The moment I increase depth > 2, I start getting a lot of network errors such as "socket hang up" or "tunneling socket could not be established". If I slip down to depth 2, it works fine. This behavior seems to consistent regardless of what I crawl. For example, I was able to recreate this on htttps://www.yahoo.com. All that being said, I don't see how js-crawler changes any behavior in the way it calls request to cause this. I've been staring at request and http documentation without any luck. Manipulating js-crawler code to use an http.Agent with maxSockets didn't seem to have an effect. So looking for any help I can get on what's causing this.

**Comment by antivanov** [comment] 2015-09-05 18:17
Needs some investigation, I think too many requests may be piling up and we may need some sort of throttling mechanism. Another thing is that we may make new http requests before all the resources are properly released for the previous ones. I will take a look.

**Comment by antivanov** [comment] 2015-09-06 17:11
This might have been addressed by the limiting the rate of HTTP requests https://github.com/antivanov/js-crawler/commit/fa6e3c527a1ea6f0422cd4ef2d923d0e989654e7. The maximum number of HTTP requests made per second is now 100.  Please, let me know if the issue is still reproducible with the latest version. If it is then some additional investigation may be needed

**Comment by marshmellow1328** [comment] 2015-09-10 21:24
I think the throttling has helped, but having problems confirming. I believe this commit broke the approach for only crawling a URL once. I placed a counter for URLs crawled. Crawling the same site with an older version, I got 324 URLs crawled (with a few errors). With the latest version I was going over 5000. I noticed a 404 for the same URL. My suspicion is all the URLs are queued up, but they're not marked as crawled until a response is returned. So page1 has a link to page3. Before page3 can be crawled and added to list of crawled pages, page2 has a link to page3 and page3 is added to list to be crawled again. Eventually the throttling catches up and page3 gets crawled twice.

**Comment by antivanov** [comment] 2015-09-11 19:20
> My suspicion is all the URLs are queued up, but they're not marked as crawled until a response is returned.

Definitely this is a regression, now urls are queued up and not excluded from crawling in case they have already been crawled, I will fix this shortly.

And it looks like even before the latest changes we implicitly relied on some timing details and in certain situations the same URL could have been crawled twice.

**Comment by antivanov** [comment] 2015-09-11 20:40
I checked the latest version and did not find any issues when some url would be crawled twice, it might be that in the older version some urls were not crawled for some reason (running out of network connections and failing to fetch all the urls?).

If you want to check whether some url is visited twice you can try to use an approach similar in a new example that was added:

```javascript
var Crawler = require("js-crawler");

var crawledUrls = {};

new Crawler().configure({
  depth: 2,
  maxRequestsPerSecond: 5
}).crawl("http://www.yahoo.com",
  function onSuccess(page) {
    if (crawledUrls[page.url]) {
      console.log('WARNING: url was already crawled before', page.url);
    }
    crawledUrls[page.url] = true;
    console.log(page.url);
  },
  function onFailure(status) {
    console.log('ERROR', status.url, status.error);
  }
);
```

In case some urls are being crawled twice which I could not reproduce, then we can create a separate issue for this and fix it.

Apart from this I also plan to add another way of throttling the crawler: not by the number of requests per second, but by the number of allowed concurrent requests. I will comment on this issue when it is implemented. Looks like a more natural way to manage limited network bandwidth.

**Comment by antivanov** [comment] 2015-09-14 21:19
Should now be fixed, please, report any other issues/regressions.

**Closed by antivanov** 2015-09-14 21:19 UTC
Labels: bug, question
